### PR TITLE
Upgrading Nan in order to provide Node 4 support

### PR DESCRIPTION
**Pull request by edsadr**

### CODE REVIEW

**Comment by eelcocramer** [comment]
Thank you for this PR. Good work. I will take a look at it in the next couple of days.

**Comment by edsadr** [comment]
Still left to make it pass for windows with node < 0.12  ... I will take a look later, need to configure a virtual machine with that config to test

**Comment by edsadr** [comment]
would be nice if we can land this soon, so they can take the module out of this list: https://github.com/nodejs/node/issues/2798

**Comment by eelcocramer** [comment]
Was the vagrantfile committed on purpose?

**Comment by edsadr** [comment]
yes... so people can actually test in Linux ... I can remove it if you don't want to include it

**Comment by edsadr** [comment]
Can't duplicate this locally, is building properly for me in windows 10 with Node 0.10.40 and VS 2015 Community, any idea @eelcocramer ?

**Comment by eelcocramer** [comment]
I think the master branch is not compiling on appveyor either. I haven't figured that out yet.

Sorry for the delays but I'm AFK for most of the time until the end of the month.

**Comment by eelcocramer** [comment]
Merged this. I like the idea of being able to build for Linux from OSX or Windows but I removed the Vagrantfile in favour of Docker.

I published a new version 1.2.5 on npm.

**Pull request merged**
