### PR TITLE
Handle reconnection in listen() method

### PR DESCRIPTION
**Pull request by atilag**
As per issue #115 , I did some changes in the code.
Changelog:
* listen() method will not exit until there's an explicit call to close().
* If a client disconnects, listen() can still handle new connections.
* Calling listen() more than once is not allowed.
* Better error handling in the server part.
* New server and client test in the experiments folder

### CODE REVIEW

**Comment by eelcocramer** [comment]
Thanks!

**Comment by eelcocramer** [comment]
2 questions:

1. There are no changes to the API?
2. Is it worth to wait for #144 before publishing this to npm?

I've merged this into the `next-release` branch.

**Comment by atilag** [comment]
1. There's no change to the API, just changed the behavior. The only change that would mean changes in existing code is that listen() cannot be called twice in the same server instance.
2. No, I would land this PR first. Actually, I will take a closer look to what I proposed in bug #144 because that would require a lot changes, so there must be a compelling use-case for it to justify it's implementation. Currently, you can have multiple server instances listening in different channels, but this will consume more memory than a handling this behavior in one instance.

**Comment by eelcocramer** [comment]
Closing this as it is merged into the `next-release` branch. Though I notice that you merged `master` into the branch with this PR. There seem to me no changes in this merge is this correct?

**Comment by meisterlampe** [comment]
@atilag Running multiple instances of my server-application that listen on different channels is not working for me (or did you mean, that it will work after this PR beeing merged? Then forget my post :-) ). 

I get the error: `Couldn't bind bluetooth socket. errno:98` (tried with different channels and different UUIDs for the instances)
I want my server to talk to more than one client at the same time. If I just connect a second device while running only a single instance, the devices connects but the listen-callback is not called.
Any idea on how to get this working?

**Comment by atilag** [comment]
@meisterlampe  I was wrong and you are right indeed. There's no way yo create multiple instances of the server, the second instance will always fail at creation. I'll try to implement the multi-listen feature stated in #144 ASAP.

**Comment by meisterlampe** [comment]
That would be great. Thanks for all your effort!

**Comment by eelcocramer** [comment]
Just published version 2.1.2 that includes this PR.

**Pull request closed without merging**
