### PR TITLE
Bluetooth RFCOMM Server support added:

### PR DESCRIPTION
**Pull request by atilag**
* Async RFCOMM Server socket
* Use SDP Server for advertising the service
* Backward compatible with client code
* Works only on Linux (for now)

### CODE REVIEW

**Comment by eelcocramer** [comment]
I've added this PR to the `next-release` branch. Thanks.

**Comment by eelcocramer** [comment]
I've merged this into the `next-release` branch and made some changes to fix loading of the scripts on other platforms than Linux.

As I'm not currently planning on using and maintaining the server code myself I would like to ask you if I can add you as a collaborator to this project. This would allow you to push to the repository and allow me to assign issues to you :-)

**Comment by atilag** [comment]
Great news! and sure, I'll maintain that code, no problem :)

**Comment by eelcocramer** [comment]
Cool!

I'll take care of this stuff somewhere next week. Thanks a lot!

**Comment by eelcocramer** [comment]
Hi,

I've added documentation for the server to the readme. Can you please check if this works for you?

https://github.com/eelcocramer/node-bluetooth-serial-port/blob/next-release/README.md#basic-server-usage

https://github.com/eelcocramer/node-bluetooth-serial-port/blob/next-release/README.md#bluetoothserialportserver

If so I will release this branch.

Thanks.

**Pull request merged**
