### PR TITLE
Promise, async/await syntax and fix bug

### PR DESCRIPTION
**Pull request by sandangel**
1. Fix a mistake with example in README.
2. Add promise support with bluebird.
3. Add types declaration for async function.
4. Fix bug:
There is an error TypeError: Cannot read property 'close' of undefined when you try to call function btSerial.connect before findSerialPortChannel.  
Step to reproduce:
btSerial.connect(address, 3, function(){}, function(){}) //you give channel a default value.

### CODE REVIEW

**Comment by eelcocramer** [comment]
Thanks for the PR. However I want to minimise the dependencies of this module and I do not want to tie this module to a specific promise library.

**Comment by sandangel** [comment]
ok I got it, let me rewrite the code with the built-in Promise support for node version > 6.4

**Comment by sandangel** [comment]
I changed syntax to promise compatible. I will test it tomorrow.

**Comment by sandangel** [comment]
I have successfully tested with client module. If you feel ok with it, I 'll fix document.
You can make a test yourselft with var Promise = require("bluebird"); Promise.promisifyAll(btSerial); then the code will by the same at my README file.

**Comment by eelcocramer** [comment]
Thanks. I will need some time to evaluate this. This changes the API without being backward compatible. Because of this I would need to release this as version v3.0.0 which is not really a problem but I want to check if it is possible to make the module more compatible with promises without breaking backward compatibility first.

**Comment by sandangel** [comment]
How about create an alias for the same function?. i.e btSerial.findChannel will alias with btSerial.findSerialPortChannel but with btSerial.findChannel you can use promise with promisify.

**Pull request closed without merging**
