### PR TITLE
d.ts file fix

### PR DESCRIPTION
**Pull request by bmadzinski**

### CODE REVIEW

**Comment by eelcocramer** [comment]
Thanks for the PR I appreciate it.

I'm not using TS myself and what I'm struggling with is that I do not understand why the TS declarations file was working before if it now needs this change?

Maybe an example TS would help me with this and I could add it to the CI pipeline so this will be automatically tested.

**Comment by bmadzinski** [comment]
Now i updated it properly. Since version 1.8 you do not use reference in TS. All imports are made by import statment. 

You can use:
`import * as types from "./export"`
to import all types from file, user variable and access it like that:
`class Car implements types.Viehicle{
    maxSpeed:  number;
}`

or you can explicitly import only some of types:
`import { Person, Viehicle } from "./export";`
and use it like this:
`class Motorcycle implements Viehicle{
    maxSpeed:  number;
}`

More about that can be found [here](https://www.typescriptlang.org/docs/handbook/modules.html)

**Comment by eelcocramer** [comment]
Thank you

**Comment by eelcocramer** [comment]
Merged this into the branch holding the `next-release`. This PR will be closed when the next version is released.

**Pull request merged**
