### PR TITLE
Async inquire

### PR DESCRIPTION
**Pull request by kncs**
Pull request to solve issue #95 
Available only for Linux and Windows: Inquire function is now asynchrnous and an InquireSync function has been created.

### CODE REVIEW

**Comment by eelcocramer** [comment]
Thanks a lot for this PR.

Just wondering if the `inquireSync` would be useful to keep at all. It's not in there for backwards compatibility. To get this behaviour you will need to change your code after updating to a version of the module with this PR included.

**Comment by kncs** [comment]
You completely right, I did think about that problem when I designed the solution. I decided to make the inquire function asynchronous (because it's more natural in javascript) and I created the inquireSync to help people for migrate their code. To be honnest, I'm not sure that function would be usefull, but people may need a synchronous inquire.

**Comment by eelcocramer** [comment]
I've merged your code into the `kncs-asyncInquire` branch and added async inquiry for OSX to it. Still need to do some check before publishing.

**Comment by eelcocramer** [comment]
I've added OSX support and merged this together with the changes of this PR into the `next-release` branch.

So this will be included in the next release of the module. Due later this week or just after the weekend.

**Comment by eelcocramer** [comment]
Merged.

**Comment by eelcocramer** [comment]
and released in version 2.1.0

**Pull request closed without merging**
