### PR TITLE
Use Nan namespace on TryCatch and FatalException

### PR DESCRIPTION
**Pull request by ELundby45**
Fixes compilation problem with nw-gyp.

### CODE REVIEW

**Comment by eelcocramer** [comment]
Thanks a lot for the PR. I will look at it next week!

**Comment by ELundby45** [comment]
:+1: 

I was trying to create separate PRs for three different commits (four because I pushed a partial commit). It looks like all of those commits showed up in this PR however. Sorry about that. 

In short:
2d001ed: Fixes a problem preventing compilation using nw-gyp on Windows
3d1bf9e Is a revised version of my previous PR for listPairedDevices on Windows updated to work with the latest code on master 
751c068 and 2191bcb Fixes a problem with large writes on Windows

**Comment by eelcocramer** [comment]
No problem. That happens if you push your changes to the same branch you used for the initial PR.

**Comment by eelcocramer** [comment]
I've added the changes to the `next-release` branch. Thanks.

**Pull request merged**
