### PR TITLE
Basic ListPairedDevices for Windows

### PR DESCRIPTION
**Pull request by ELundby45**
Adds ListPairedDevices for Windows, is virtually instantaneous and
compared to inquiry.  The code could be greatly improved. The SPP
channel is currently being hard coded to 1, ideally this would be
populated using SDP. There is code duplication with Inquiry().

### CODE REVIEW

**Comment by ELundby45** [comment]
@langholz I have made flags a `const DWORD`. `querySetSize` however is an input + an output in WSALookupServiceNext according to the docs:


    INT WSALookupServiceNext(
      _In_     HANDLE hLookup,
      _In_     DWORD dwControlFlags,
      _Inout_  LPDWORD lpdwBufferLength,
      _Out_    LPWSAQUERYSET lpqsResults
    );


I also added a check to the device name. If there is no device name, the address string will be returned in order to match the other platforms.

**Comment by ELundby45** [comment]
Example output:

`node .\experiments\paired-devices-test.js`
```javascript
{ name: 'testDevice-WCC',
  address: '00:04:3E:08:21:D1',
  services: [ { channel: 1, name: 'SPP' } ] }
{ name: 'testDevice-BCY',
  address: '00:04:3E:31:5C:18',
  services: [ { channel: 1, name: 'SPP' } ] }
{ name: '45:02:A3:9F:28:A4',
  address: '45:02:A3:9F:28:A4',
  services: [ { channel: 1, name: 'SPP' } ] }
```

**Comment by eelcocramer** [comment]
I will close this issue in a few days as it has almost been a year and it is stil nog merged in. I'm sorry I'm unable to test and merge this myself. I want to thank you all for contributing!

**Comment by ELundby45** [comment]
An updated version of this PR was merged in #107.

**Pull request closed without merging**
