### PR TITLE
Add cross-platform continuous integration

### PR DESCRIPTION
**Pull request by mackwic**
This is a WIP.
I pushed the PR mainly because it's easier to check the status-pill. (also because it's still open to discussion)

I plan to have the following build matrix:
- node.js 0.10.last, 0.11.last, 0.12.last
- iojs last

Against the following platforms:
- ubuntu LTS
- mac osx 10.9.5
- windows

The build step is the following:
- boot the fresh CI environment
- run a `node-gyp configure && node-gyp build`
- load a dummy `test.js` which require `bluetooth-serial-port` and `exit 0` if successfully loaded
- the test pass if a `BluetoothSerialPort.node` has been generated and if `test.js` returns 0

TODO:
- [x] dummy test script
- [x] ubuntu LTS builds via travis-ci
- [x] osx 10.9.5 builds via travis-ci if they are nice enough (http://docs.travis-ci.com/user/multi-os/)
  - [x] asked to travis [ref](https://github.com/eelcocramer/node-bluetooth-serial-port/pull/58#issuecomment-74565042)
  - [x] waiting the travis reply for osx activation
  - [x] need nvm on the osx builds, waiting travis support for a solution
  - [x] implement node installation platform-specific
- [ ] windows builds via app-veyor (https://ci.appveyor.com/)

Reference project: https://github.com/mapbox/node-sqlite3

**Warning** because CI fixing tends to produce a lot of commits, I will heavily `git commit --amend && git push --force` to keep the history clean. Don't pull without asking unless you want infinite merge hell. You have been warned.

### CODE REVIEW

**Comment by eelcocramer** [comment]
:-)

Thanks for the effort. Very useful.

**Comment by mackwic** [comment]
Yeah. I am really bored by infinitely recompiling node-bluetooth-serial port on all our possible configurations and forgetting the one hack that made the compilation ok on this specific setup. :)

**Comment by mackwic** [comment]
Hi Travis !

I am working on briging CI to the node-bluetooth-serial-port project (https://github.com/eelcocramer/node-bluetooth-serial-port/pull/58)

Basically, it’s the **only** open-source, cross-platform, implementation of Bluetooth 2 SPP if we except `javax.bluetooth.*` (you can check this assertion).

We would be very glad if you could add our project to the waiting queue for osx builds.

thank you for you wonderful service,
--  
mackwic
mackwic@42.epimeros.org

**Comment by eelcocramer** [comment]
If you need a special hack on a specific setup, please let me know. Things should be sort of generic on all platforms since the last release. Altough win is currently disabled as i cannot test it myself: #53

**Comment by mackwic** [comment]
Build on linux seems ok. I send a mail to Travis asking for the osx builds (see above), working on the windows build later.

**Comment by mackwic** [comment]
@eelcocramer Yeah, the build process has been far better recently.
On 1.1.2, some hacks were needed to compile correctly with nw.js. Now that we have Nan, it should be ok. If there's any issue with 1.2.1 and nw.js, I will add it to the matrix build.

**Comment by mackwic** [comment]
-- Please reply above this line --


Hi Mackwic,

Thanks for the email.

Is the project open source or private? I can't seem to find it on
travis-ci.org so can't enable it.

Kind Regards,

Josh

How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]
--
Josh Kalderimis
support@travis-ci.com


Links:
------
[1]
https://secure.helpscout.net/satisfaction/46888492/record/180408369/1/
[2]
https://secure.helpscout.net/satisfaction/46888492/record/180408369/2/
[3]
https://secure.helpscout.net/satisfaction/46888492/record/180408369/3/

**Comment by mackwic** [comment]
@eelcocramer could you enable travis for this repo ?
Go on https://travis-ci.com/signin, then autorize travis, and enable the automated build for this repository.
This way, the cool travis guys could enable osx build for bluetooth-serial-port. :smile:

**Comment by eelcocramer** [comment]
Very cool indeed! I've just enabled automated builds for the repo. Do I need to pull in your changes? Thank you for your effort!

**Comment by mackwic** [comment]
Excellent ! I think it will be ok as the PR are cloned on a special branch `pull/ID/head:BRANCHNAME` (here: `pull/58/head:master` [ref](https://help.github.com/articles/checking-out-pull-requests-locally/).
I mail the travis team and we will see.

**Comment by mackwic** [comment]
Hi Josh, thanks for the very quick answer !

Travis was enabled on my fork, but not on the blessed repo.

This should be fixed now and you should see `eelcocramer/node-bluetooth-serial-port` as an open-source repo.

Tell me if you need the changes to be merged before the activation, we can do that during the day.

Thanks again,
--  
mackwic
mackwic@42.epimeros.org

-----Original Message-----
De: Travis CI Support <support@travis-ci.com>
Répondre: Travis CI Support <support@travis-ci.com>>
Date: 17 février 2015 at 00:53:33
À: Mackwic <mackwic@42.epimeros.org>>
Cc: reply@reply.github.com <reply@reply.github.com>>
Sujet:  Re: OSX build for the node-bluetooth-serial-port project

> -- Please reply above this line --
>  
>  
> Hi Mackwic,
>  
> Thanks for the email.
>  
> Is the project open source or private? I can't seem to find it on
> travis-ci.org so can't enable it.
>  
> Kind Regards,
>  
> Josh
>  
> How would you rate my reply?
> Great [1] Okay [2] Not Good [3]
> --
> Josh Kalderimis
> support@travis-ci.com
>  
>  
> Links:
> ------
> [1]
> https://secure.helpscout.net/satisfaction/46888492/record/180408369/1/
> [2]
> https://secure.helpscout.net/satisfaction/46888492/record/180408369/2/
> [3]
> https://secure.helpscout.net/satisfaction/46888492/record/180408369/3/
>  
>  
>

**Comment by mackwic** [comment]
-- Please reply above this line --


Hi Mackwic,

Thanks for the extra details.

I am wondering if there's some kind of misunderstanding. In your
original email you requested to be added to the waiting queue for OSX
builds. 

On travis-ci.org you can simply opt into using OSX build environment
by specifying `osx` as a language.

Did you mean to request enabling the repository for multi-os testing? 

Cheers,


How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]
--
Sven Fuchs
support@travis-ci.com


Links:
------
[1]
https://secure.helpscout.net/satisfaction/46888492/record/180589456/1/
[2]
https://secure.helpscout.net/satisfaction/46888492/record/180589456/2/
[3]
https://secure.helpscout.net/satisfaction/46888492/record/180589456/3/

**Comment by mackwic** [comment]
Hi Sven,

It’s possible that a misunderstanding exist.

The [documentation](http://docs.travis-ci.com/user/multi-os/) explicitly states that you don’t accept request multi-os request as you are at full capacity.
So I don’t ask for it now, but when you will have the sufficient capacity.

Does it mean that it is possible right now ? We would be really glad if you could enable the multi-os testing today. That would be simply awesome. :)

Regards,
--  
mackwic
mackwic@42.epimeros.org

-----Original Message-----
De: Travis CI Support <support@travis-ci.com>
Répondre: Travis CI Support <support@travis-ci.com>>
Date: 17 février 2015 at 10:54:14
À: Mackwic <mackwic@42.epimeros.org>>
Cc: reply@reply.github.com <reply@reply.github.com>>
Sujet:  Re: OSX build for the node-bluetooth-serial-port project

> -- Please reply above this line --
>  
>  
> Hi Mackwic,
>  
> Thanks for the extra details.
>  
> I am wondering if there's some kind of misunderstanding. In your
> original email you requested to be added to the waiting queue for OSX
> builds.
>  
> On travis-ci.org you can simply opt into using OSX build environment
> by specifying `osx` as a language.
>  
> Did you mean to request enabling the repository for multi-os testing?
>  
> Cheers,
>  
>  
> How would you rate my reply?
> Great [1] Okay [2] Not Good [3]
> --
> Sven Fuchs
> support@travis-ci.com
>  
>  
> Links:
> ------
> [1]
> https://secure.helpscout.net/satisfaction/46888492/record/180589456/1/
> [2]
> https://secure.helpscout.net/satisfaction/46888492/record/180589456/2/
> [3]
> https://secure.helpscout.net/satisfaction/46888492/record/180589456/3/
>  
>  
>  
>  
>  
>  
>

**Comment by mackwic** [comment]
-- Please reply above this line --


Hi Mackwic,

I have enabled multi-os builds for your repository
eelcocramer/node-bluetooth-serial-port

Enjoy!

Please let us know if you have any further questions.

Cheers,

How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]
--
Sven Fuchs
support@travis-ci.com


Links:
------
[1]
https://secure.helpscout.net/satisfaction/46888492/record/180617186/1/
[2]
https://secure.helpscout.net/satisfaction/46888492/record/180617186/2/
[3]
https://secure.helpscout.net/satisfaction/46888492/record/180617186/3/

**Comment by mackwic** [comment]
Hi Travis !

The osx build have failed because `nvm` is not brewed. As it’s before-before-install, we can’t do much against it.

https://travis-ci.org/eelcocramer/node-bluetooth-serial-port/builds/51065696

I can see 3 solutions:
1) you can add `nvm` seamlessly on all osx. Good.
2) you hack the build so that it doesn’t crash on `nvm use $version`, so that we can do it ourself. No problem
3) we hack the build by changing to a supported language matrix like ruby (so that the number of jobs is ok), and do all the install process by hand.

We can do whatever you like. Do you have a suggestion ?

Kind regards,
--  
mackwic
mackwic@42.epimeros.org

-----Original Message-----
De: Travis CI Support <support@travis-ci.com>
Répondre: Travis CI Support <support@travis-ci.com>>
Date: 17 février 2015 at 12:01:30
À: Mackwic <mackwic@42.epimeros.org>>
Cc: reply@reply.github.com <reply@reply.github.com>>
Sujet:  Re: OSX build for the node-bluetooth-serial-port project

> -- Please reply above this line --
>  
>  
> Hi Mackwic,
>  
> I have enabled multi-os builds for your repository
> eelcocramer/node-bluetooth-serial-port
>  
> Enjoy!
>  
> Please let us know if you have any further questions.
>  
> Cheers,
>  
> How would you rate my reply?
> Great [1] Okay [2] Not Good [3]
> --
> Sven Fuchs
> support@travis-ci.com
>  
>  
> Links:
> ------
> [1]
> https://secure.helpscout.net/satisfaction/46888492/record/180617186/1/
> [2]
> https://secure.helpscout.net/satisfaction/46888492/record/180617186/2/
> [3]
> https://secure.helpscout.net/satisfaction/46888492/record/180617186/3/
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
>

**Comment by mackwic** [comment]
-- Please reply above this line --


Hi Mackwic,

You are right, there are a number of limitations as mentioned in the
docs. See https://github.com/travis-ci/travis-ci/issues/2320 [1] for
details.

You'll need to find a way to work around nvm not being preinstalled,
as in your solution 3).

Cheers,

Links:
------
[1] https://github.com/travis-ci/travis-ci/issues/2320


How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]
--
Sven Fuchs
support@travis-ci.com


Links:
------
[1]
https://secure.helpscout.net/satisfaction/46888492/record/180633076/1/
[2]
https://secure.helpscout.net/satisfaction/46888492/record/180633076/2/
[3]
https://secure.helpscout.net/satisfaction/46888492/record/180633076/3/

**Comment by mackwic** [comment]
So, the build osx and linux is ok ! :) :tada:

**Comment by eelcocramer** [comment]
Nice!

**Comment by mackwic** [comment]
@eelcocramer Errors on the windows build: https://ci.appveyor.com/project/mackwic/node-bluetooth-serial-port/build/1.0.2/job/00u74x1yncmgldyn#L36

**Comment by mackwic** [comment]
I think the PR's work is done and it would be ok to merge and fix the build as a separate PR. On my side, I am satisfied. I woulds have like better build times but hey, free cross-platform CI is already awesome.

You should activate Appveyor for this repo so that you can take over the CI.

**Comment by eelcocramer** [comment]
Thanks again. I will look into the PR and pull soon.

**Comment by eelcocramer** [comment]
Only io.js is still failing on windows. Any ideas? Is this in the appveyor setup?

https://ci.appveyor.com/project/eelcocramer/node-bluetooth-serial-port/build/1.0.3/job/h7rkg4o4uc58dj0a

**Comment by mackwic** [comment]
Yeah, it's an error in the app veyor setup. I will fix it during the day

**Comment by eelcocramer** [comment]
Cool. I'll wait for that with publishing version 1.2.2 to npm.

**Comment by eelcocramer** [comment]
Opened issue #61 for this. I've pushed 1.2.2 to npm without support for ci on windows 64bits and windows io.js for now.

**Pull request merged**
