### PR TITLE
Fix typescript example

### PR DESCRIPTION
**Pull request by bkniffler**

### CODE REVIEW

**Comment by eelcocramer** [comment]
Thank your for contributing. LGTM.

**Comment by bkniffler** [comment]
You're welcome. Thanks for creating and maintaining this cool library, it has helped me a ton for using a bluetooth barcode scanner on a raspberry pi, where other methods have failed :)

**Comment by eelcocramer** [comment]
Thanks. Always great to hear what folks are creating!

**Comment by eelcocramer** [comment]
Merged into the next-release branch. Will be part of version 2.2.2

**Pull request closed without merging**
